### ISSUE TITLE
Use standard Gemfile from carpentries/lesson-example

### ISSUE THREAD

**Issue by vinisalazar** [hpc-carpentry/hpc-python#39]
Hi!

I forked this repo with the intent of contributing to it.

When I tried to render the lesson locally, it failed with the following error:

```
Could not find gem 'mdl' in any of the gem sources listed in your Gemfile.
Run `bundle install` to install missing gems.
```

After running `bundle install`, the dependency was installed and I could render the lesson.

However, I propose that the template Gemfile from [carpentries/lesson-example](https://github.com/carpentries/lesson-example/blob/gh-pages/Gemfile) be used. This will ensure consistency with other lessons and thus helps to advance the development stage of this lesson. I was able to successfully render the lesson locally using this Gemfile.

I will submit a PR addressing this, but please feel free to reject it if there's a reason to use a custom Gemfile.

Best,
V

**Comment by tkphd** [comment]
Hi V,

Yes, `mdl` is [markdownlint](https://github.com/markdownlint/markdownlint), which we use to ensure good hygiene in our episodes and code snippets. This is not included in the upstream Gemfile, and most lessons do not scrub contributions this thoroughly. This is normally transparent to users and developers, as `make serve` calls `bundle install` before doing anything else.

We want to provide the folks running hpc-python with the ability to specialize the lesson for the particulars of their site and computational resources. This necessitates some small divergence from the upstream boilerplate, though we do try to keep in sync anyway. Closing this divergence would mean pushing our changes to the upstream repo -- which is not a bad idea, since there's a lot of Markdown in the Carpentries, and therefore a lot of lint.

Best,
T

**Comment by vinisalazar** [comment]
Hi @tkphd, thank you for the fast reply.

That makes total sense. I guess I got the error because I ran `bundle exec jekyll serve` rather than `make serve`.

I added the downstream dependencies to the Gemfile. It should pass your tests now, if you consider reopening #40.
